"""Export crawler output to sample_data/ (committed to the repo for inspection and the hosted dashboard).

    python export.py

Writes:
  sample_data/scholarships.db       copy of the SQLite database (all tables)
  sample_data/scholarships.csv      one row per scholarship (universal schema + score + status)
  sample_data/scholarships.json     same, with per-field evidence, score breakdown and change history
  sample_data/change_log.csv        every detected change
  sample_data/crawl_runs.csv        every crawl run
"""
import json
import sqlite3

import pandas as pd

import config
import db

OUT = config.BASE_DIR / "sample_data"


def main() -> None:
    OUT.mkdir(exist_ok=True)
    target = OUT / "scholarships.db"
    if target.exists():
        target.unlink()
    src = sqlite3.connect(config.DB_PATH)
    src.execute("VACUUM INTO ?", (str(target),))  # consistent single-file copy
    src.close()

    with db.session() as conn:
        sch = pd.read_sql_query("""SELECT s.*, src.source_type FROM scholarships s
                                   LEFT JOIN sources src ON src.url = s.official_url ORDER BY s.confidence DESC""", conn)
        sch.drop(columns=["score_breakdown"]).to_csv(OUT / "scholarships.csv", index=False)
        pd.read_sql_query("SELECT * FROM change_log ORDER BY id", conn).to_csv(OUT / "change_log.csv", index=False)
        pd.read_sql_query("SELECT * FROM crawl_runs ORDER BY run_id", conn).to_csv(OUT / "crawl_runs.csv", index=False)

        records = []
        for _, r in sch.iterrows():
            ev = conn.execute("""SELECT field, value, evidence_quote, source_url, snapshot_id, grounded, reason
                                 FROM field_evidence WHERE scholarship_id=?""", (int(r["id"]),)).fetchall()
            ch = conn.execute("""SELECT detected_at, field, old_value, new_value, note, source_url, evidence_quote
                                 FROM change_log WHERE scholarship_id=? ORDER BY id""", (int(r["id"]),)).fetchall()
            rec = {k: (None if pd.isna(v) else v) for k, v in r.items() if k not in ("score_breakdown", "eligibility_json")}
            rec["eligibility_json"] = json.loads(r["eligibility_json"] or "{}")
            rec["score_breakdown"] = json.loads(r["score_breakdown"] or "{}")
            rec["evidence"] = {e["field"]: {k: e[k] for k in e.keys() if k != "field"} for e in ev}
            rec["change_history"] = [dict(c) for c in ch]
            records.append(rec)
        (OUT / "scholarships.json").write_text(json.dumps(records, ensure_ascii=False, indent=2, default=str),
                                               encoding="utf-8")
    print(f"exported {len(records)} scholarships to {OUT}")
    update_readme(records)


def update_readme(records: list[dict]) -> None:
    """Rewrite the README 'Results' block from the database, so the numbers always match the data."""
    n = len(records)
    own = [r for r in records if r["score_breakdown"].get("owns_source")]
    verified = [r for r in records if r["verification_status"] == "VERIFIED"]
    by_status: dict[str, int] = {}
    for r in records:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
    types: dict[str, int] = {}
    for r in own:
        types[r["source_type"]] = types.get(r["source_type"], 0) + 1
    with db.session() as conn:
        changes = conn.execute("SELECT COUNT(*) FROM change_log WHERE field != 'status'").fetchone()[0]
        transitions = conn.execute("SELECT COUNT(*) FROM change_log WHERE field = 'status'").fetchone()[0]
        runs = conn.execute("SELECT COUNT(*) FROM crawl_runs WHERE notes NOT LIKE 'archive baseline%' "
                            "OR notes IS NULL").fetchone()[0]
        chg_rows = conn.execute("""SELECT c.scholarship_id, s.name, c.field, c.old_value, c.new_value, c.note
                                   FROM change_log c JOIN scholarships s ON s.id=c.scholarship_id
                                   WHERE c.field != 'status' ORDER BY c.id""").fetchall()
    stale = by_status.get("EXPIRED", 0) + by_status.get("NO_LONGER_VERIFIABLE", 0)
    lines = [
        f"_Generated by `python export.py` on {db.now_iso()[:10]} from `sample_data/scholarships.db`._", "",
        "| Brief requirement | Result |", "|---|---|",
        f"| 20+ real scholarships | **{n}** records |",
        f"| 15+ verified against primary/official sources | **{len(own)}** records whose source page belongs to the provider |",
        f"| 10+ with confidence ≥ 95% | **{len(verified)}** VERIFIED |",
        f"| 3+ source types | {', '.join(f'{k} ({v})' for k, v in sorted(types.items()))} |",
        f"| 2+ change detections | **{changes}** field changes logged (+{transitions} status transitions) |",
        f"| 2+ expired / stale | **{stale}** ({', '.join(f'{k} {v}' for k, v in sorted(by_status.items()))}) |",
        f"| Repeated runs | {runs} crawl runs (see `crawl_runs`) |", "",
        "**VERIFIED records:**", "",
    ]
    for r in sorted(verified, key=lambda r: -r["confidence"]):
        lines.append(f"- {r['confidence']:.1f}%  {r['name']}  ({r['official_url']})")
    if chg_rows:
        lines += ["", "**Detected changes:**", ""]
        for c in chg_rows:
            lines.append(f"- #{c['scholarship_id']} {c['name']}: `{c['field']}` {c['old_value']} → {c['new_value']} ({c['note']})")
    readme = config.BASE_DIR / "README.md"
    text = readme.read_text(encoding="utf-8")
    start, end = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"
    if start in text and end in text:
        head, rest = text.split(start, 1)
        _, tail = rest.split(end, 1)
        readme.write_text(head + start + "\n" + "\n".join(lines) + "\n" + end + tail, encoding="utf-8")
        print("README results updated")


if __name__ == "__main__":
    main()
